SYNCQT.HEADER_FILES = ../../include/QtCUDA/qtcuda.h ../../include/QtCUDA/GL
SYNCQT.HEADER_CLASSES = ../../include/QtCUDA/QtCUDA
SYNCQT.PRIVATE_HEADER_FILES =
SYNCQT.QPA_HEADER_FILES = 
SYNCQT.INJECTIONS = 
